name: 自动更新和发布广告规则

permissions:
  contents: write

on:
  schedule:
    - cron: '0 * * * *'   # 每小时运行一次
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: 读取本地缓存 SHA
        id: load_hash
        run: |
          if [ -f scripts/.last_hash ]; then
            echo "last_sha=$(cat scripts/.last_hash)" >> $GITHUB_OUTPUT
          else
            echo "last_sha=" >> $GITHUB_OUTPUT
          fi

      - name: 检查上游最新提交 SHA
        id: check_upstream
        run: |
          echo "🔍 正在检查上游是否更新..."
          LATEST_SHA=$(curl -s "https://api.github.com/repos/TG-Twilight/AWAvenue-Ads-Rule/commits?path=Filters/AWAvenue-Ads-Rule-Clash-Classical.yaml&sha=main" | jq -r '.[0].sha')
          echo "latest_sha=${LATEST_SHA}" >> $GITHUB_OUTPUT

          if [ "${{ steps.load_hash.outputs.last_sha }}" = "$LATEST_SHA" ]; then
            echo "🟢 上游未更新，终止工作流。"
            exit 0
          fi

      - name: 检出代码
        uses: actions/checkout@v4

      - name: 配置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖包
        run: pip install requests

      - name: 运行转换脚本
        run: python scripts/convert_rule.py

      - name: 检查是否有变更
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: 提交变更
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add AWAvenue-Ads-Rule-Clash-Classical.list scripts/.last_hash
          git commit -m "🔄 自动更新规则"
          git push

      - name: 生成标签
        id: tag
        run: echo "tag=v$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_OUTPUT

      - name: 创建发布
        if: steps.check_changes.outputs.changed == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: 自动发布 ${{ steps.tag.outputs.tag }}
          body: |
            自动同步更新源规则并刷新 CDN 缓存。
            - 来源：https://github.com/TG-Twilight/AWAvenue-Ads-Rule
            - 时间戳：${{ steps.tag.outputs.tag }}
          files: AWAvenue-Ads-Rule-Clash-Classical.list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}