name: Update GeoLite2 ASN

on:
  schedule:
    - cron: '0 0 * * *'  # 每天北京时间早上8点
  workflow_dispatch:

permissions:
  contents: write  # ✅ 允许工作流推送到仓库

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}
      DB_URL: "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN&license_key=${{ secrets.MAXMIND_LICENSE_KEY }}&suffix=tar.gz"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl tar

      - name: Get latest version info (header only)
        id: check
        run: |
          HEADERS=$(curl -sI "${DB_URL}")
          ETAG=$(echo "$HEADERS" | grep -i ETag | awk '{print $2}' | tr -d '\r"')
          echo "etag=$ETAG" >> $GITHUB_OUTPUT
          echo "Latest ETag: $ETAG"

      - name: Compare with last version
        id: compare
        run: |
          mkdir -p .cache
          PREV=$(cat .cache/etag.txt 2>/dev/null || echo "none")
          CURR="${{ steps.check.outputs.etag }}"
          echo "Previous: $PREV"
          echo "Current : $CURR"
          if [ "$PREV" = "$CURR" ]; then
            echo "no_update=true" >> $GITHUB_OUTPUT
          else
            echo "no_update=false" >> $GITHUB_OUTPUT
            echo "$CURR" > .cache/etag.txt
          fi

      - name: Stop if no new version
        if: steps.compare.outputs.no_update == 'true'
        run: |
          echo "✅ No new version found, exiting."
          exit 0

      - name: Download and extract new GeoLite2-ASN
        run: |
          curl -L -o GeoLite2-ASN.tar.gz "${DB_URL}"
          tar -xzf GeoLite2-ASN.tar.gz
          FILE=$(find . -name "GeoLite2-ASN.mmdb" | head -n 1)
          mkdir -p geo
          mv "$FILE" geo/GeoLite2-ASN.mmdb

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add geo/GeoLite2-ASN.mmdb .cache/etag.txt
          git commit -m "update: GeoLite2-ASN.mmdb $(date -u '+%Y-%m-%d %H:%M:%S UTC')" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
